package store

import (
	"database/sql"
	"errors"
	"time"

	"github.com/bfalcher/certguard/internal/model"
)

// ErrNotFound is returned when a lookup matches no row.
var ErrNotFound = errors.New("not found")

// --- Users ---

// CreateUser inserts a user. passwordHash must already be bcrypt-hashed.
func (s *Store) CreateUser(email, passwordHash, role string) (*model.User, error) {
	now := time.Now().UTC()
	id, err := s.insertReturningID(
		`INSERT INTO users (email, password_hash, role, created_at) VALUES (?,?,?,?)`,
		email, passwordHash, role, now.Format(rfc3339))
	if err != nil {
		return nil, err
	}
	return s.GetUserByID(id)
}

// CountUsers reports how many users exist (used for first-run bootstrap hints).
func (s *Store) CountUsers() (int, error) {
	var n int
	err := s.queryRow(`SELECT COUNT(*) FROM users`).Scan(&n)
	return n, err
}

const userCols = `SELECT id, email, password_hash, role, created_at FROM users`

func (s *Store) GetUserByID(id int64) (*model.User, error) {
	return scanUser(s.queryRow(userCols+` WHERE id=?`, id))
}

func (s *Store) GetUserByEmail(email string) (*model.User, error) {
	return scanUser(s.queryRow(userCols+` WHERE email=?`, email))
}

func (s *Store) ListUsers() ([]*model.User, error) {
	rows, err := s.query(userCols + ` ORDER BY created_at ASC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*model.User
	for rows.Next() {
		u, err := scanUser(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

func scanUser(r rowScanner) (*model.User, error) {
	var u model.User
	var createdAt string
	err := r.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.Role, &createdAt)
	if err == sql.ErrNoRows {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	u.CreatedAt = parseTime(createdAt)
	return &u, nil
}

// --- API tokens ---

// CreateToken stores a token hash for a user. The plaintext is generated by the
// caller (via auth.GenerateToken) and never persisted.
func (s *Store) CreateToken(userID int64, name, tokenHash string) (*model.APIToken, error) {
	now := time.Now().UTC()
	id, err := s.insertReturningID(
		`INSERT INTO api_tokens (user_id, name, token_hash, created_at) VALUES (?,?,?,?)`,
		userID, name, tokenHash, now.Format(rfc3339))
	if err != nil {
		return nil, err
	}
	return &model.APIToken{ID: id, UserID: userID, Name: name, CreatedAt: now}, nil
}

// UserByTokenHash resolves a token hash to its owner and stamps last_used_at.
func (s *Store) UserByTokenHash(tokenHash string) (*model.User, error) {
	var userID int64
	err := s.queryRow(`SELECT user_id FROM api_tokens WHERE token_hash=?`, tokenHash).Scan(&userID)
	if err == sql.ErrNoRows {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	_, _ = s.exec(`UPDATE api_tokens SET last_used_at=? WHERE token_hash=?`,
		time.Now().UTC().Format(rfc3339), tokenHash)
	return s.GetUserByID(userID)
}

// ListTokens returns all tokens for a user (without plaintext, which is gone).
func (s *Store) ListTokens(userID int64) ([]*model.APIToken, error) {
	rows, err := s.query(
		`SELECT id, user_id, name, created_at, last_used_at FROM api_tokens WHERE user_id=? ORDER BY created_at ASC`,
		userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*model.APIToken
	for rows.Next() {
		var t model.APIToken
		var createdAt string
		var lastUsed sql.NullString
		if err := rows.Scan(&t.ID, &t.UserID, &t.Name, &createdAt, &lastUsed); err != nil {
			return nil, err
		}
		t.CreatedAt = parseTime(createdAt)
		if lastUsed.Valid {
			tm := parseTime(lastUsed.String)
			t.LastUsedAt = &tm
		}
		out = append(out, &t)
	}
	return out, rows.Err()
}

// --- Sessions ---

// CreateSession stores a session hash with an expiry.
func (s *Store) CreateSession(userID int64, sessionHash string, expiresAt time.Time) error {
	_, err := s.exec(
		`INSERT INTO sessions (user_id, session_hash, created_at, expires_at) VALUES (?,?,?,?)`,
		userID, sessionHash, time.Now().UTC().Format(rfc3339), expiresAt.UTC().Format(rfc3339))
	return err
}

// UserBySessionHash resolves a live (unexpired) session to its user. Expired
// sessions are deleted and treated as not found.
func (s *Store) UserBySessionHash(sessionHash string) (*model.User, error) {
	var userID int64
	var expiresAt string
	err := s.queryRow(`SELECT user_id, expires_at FROM sessions WHERE session_hash=?`, sessionHash).
		Scan(&userID, &expiresAt)
	if err == sql.ErrNoRows {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	if time.Now().UTC().After(parseTime(expiresAt)) {
		_, _ = s.exec(`DELETE FROM sessions WHERE session_hash=?`, sessionHash)
		return nil, ErrNotFound
	}
	return s.GetUserByID(userID)
}

// DeleteSession removes a session (logout).
func (s *Store) DeleteSession(sessionHash string) error {
	_, err := s.exec(`DELETE FROM sessions WHERE session_hash=?`, sessionHash)
	return err
}
